name: Work 1 Dorx
on: [push]
jobs: 
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Print Something
      run: echo "Hola Pitaya!"
        echo "Impresion 1"
        echo "Impresion 2"
        echo "Impresion 3"
